server:
  # 服务端口
  port: 7090
  servlet:
    # 项目上下文
    context-path: /api
    # 文件上传大小限制
    session:
      timeout: PT60M

spring:
  mvc:
    # 处理favicon,即网站图标
    favicon:
      enable: false
    # 异常处理
    throw-exception-if-no-handler-found: true
    web:
      resources:
        add-mappings: false

  # 数据库配置
  datasource:
    url: jdbc:mysql://localhost/happy_cloud_disk?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: HikariCPDatasource
      minimum-idle: 5
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  #发送邮件配置
  mail:
    host: smtp.qq.com
    port: 465
    username: 2862876057@qq.com
    password: xnifwztchfuwdgdhHj20011225@
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
        debug: true

  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
    timeout: 2000

project:
  folder: e:/webser/myapps/happyCloudDisk/

log:
  root:
    level: debug

admin:
  emails: test@qq.com

dev: false

qq:
  app:
    id: 12333
    key: 2222222
  url:
    authorization: https://graph.qq.com/oauth2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s
    access-token: https://graph.qq.com/oauth2.0/token?grant_type=authorization_code&client_id=%s&client_secret=%s&code=%s&redirect_uri=%s
    openid: https://graph.qq.com/oauth2.0/me?access_token=%S
    user-info: https://graph.qq.com/user/get_user_info?access_token=%s&oauth_consumer_key=%s&openid=%s
  redirect: http://easypan.wuhancoder.com/qqlogincalback
